baseurl:
url: https://zuti666.github.io
title: 英飞
subtitle: "the more hardworking, the luckier"
description: "Zuti's personal page"
date_format: "ordinal"
# timezone: Asia/Xi'an
encoding: "utf-8"
side_bar_repo_limit: 5

author: zuti666
organization: 
organization_url: 
github_username: zuti666
location: Xi'an, China
email: 

# Navigation
navs:
  -
    href: /
    label: Homepage

  -
    href: /categories/
    label: Blogs

  -
    href: /project/
    label: Project

  -
    href: /wiki/
    label: Wiki

  -
    href: /about me/
    label: About me

  # -
  #   href: /links/
  #   label: Links

# RSS
subscribe_rss: /feed.xml

# Jekyll
markdown: kramdown
kramdown:
    input: GFM
    math_engine: katex
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
plugins:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
    project:
        output: true
        permalink: /project/:path/

repository: chauby/chauby.github.io

# Search
simple_jekyll_search:
    fulltext: false # full text search enable
    limit: 10 # limitation of the search results to show

# Analytics
google:
    analytics_id: UA-80669434-1
github: [metadata]
